Master documentserver
threefoldtech/vdc-solutions-charts pull request #3
Opened 2020-12-09 13:21 UTC by tobiaschielens

2020-12-15 10:29 UTC, m-motawea requested changes
please add `readme` to explain the required config for the chart

you can use https://github.com/threefoldtech/vdc-solutions-charts/blob/master/charts/kube-prometheus-stack/README.md as an example

2020-12-15 15:26 UTC, AhmedHanafy725 requested changes
meeting chart in another PR, Can we remove it from this one?

can you please follow these [steps](https://github.com/threefoldtech/vdc-solutions-charts#addingmodifying-a-chart-in-the-repo) for adding the chart?

2020-12-23 11:11 UTC, tobiaschielens commented
Added readme + removed meetings + added resource limits

2021-01-04 08:49 UTC, tobiaschielens commented
Added the steps from https://github.com/threefoldtech/vdc-solutions-charts#addingmodifying-a-chart-in-the-repo

2021-01-05 15:23 UTC, ashraffouda commented on charts/documentserver/values.yaml
> +ingress:
do we need to expose this solution as well?
if so plz refere to the comment on filebrowser pr
https://github.com/threefoldtech/vdc-solutions-charts/pull/4#discussion_r551987193

2021-01-07 17:41 UTC, ken-de-moor commented
To be reviewed

2021-01-12 12:47 UTC, tobiaschielens commented
The package works on the threefold vdc
helm install documentserver ./ --set ingress.hosts[0]=helmtest.jimber.io --set ingress.certresolver=gridca

2021-01-18 09:00 UTC, closed without merging